#!/bin/bash
#########################################################
# postinst
#
# Post-installation script that is executed after the
# Debian package is installed
#
# Original Author: DA
# Copyright: (c) 2016 CyberRadio Solutions, Inc.  All rights
#     reserved.
#
#########################################################

# Make directories /public and /public/ndrDemoGui if needed
mkdir -p /public/ndrDemoGui

# Change directory permissions on /public and /public/ndrDemoGui
chmod 777 /public /public/ndrDemoGui

# After installing replacement Python code modules, 
# delete previously compiled *.pyc files in order to force
# a recompile.
rm -f $(find /usr/lib/python2.7/dist-packages/CyberRadio -name '*.pyc')

for TEMPLATE in `find /usr/{local/,}lib -name "flow_graph.tmpl"`
do
	IFS=''
	grep -q "Qt App Signal Handlers" $TEMPLATE
	if [ $? -ne 0 ]
	then
		echo "MODDING $TEMPLATE"
		while read LINE
		do
			sed -i "s/    def quitting():/    $LINE\n    def quitting():/" $TEMPLATE
			echo "-> $LINE"
		done <<< "##  vvvv  gr-CyberRadio  vvvv
\##Qt App Signal Handlers.
from PyQt4.QtCore import QTimer
import signal
signal.signal(signal.SIGINT, lambda sig,_: qapp.quit())
signal.signal(signal.SIGTERM, lambda sig,_: qapp.quit())
timer = QTimer()
timer.start(200)
timer.timeout.connect(lambda: None)
\##  ^^^^  gr-CyberRadio  ^^^^
"
	else
		echo "SKIPPING $TEMPLATE"
	fi
done

for TEMPLATE in `find /usr/{local/,}lib -name "flow_graph.tmpl"`
do
	IFS=''
	grep -q "Wait for QT flowgraph to end" $TEMPLATE
	if [ $? -ne 0 ]
	then
		echo "MODDING $TEMPLATE"
		while read LINE
		do
			sed -i "s/    def quitting():/    $LINE\n    def quitting():/" $TEMPLATE
			echo "-> $LINE"
		done <<< "##  vvvv  gr-CyberRadio  vvvv
\##Wait for QT flowgraph to end.
import threading
def doWait(tb,qapp):
    tb.wait()
    print('done waiting')
    qapp.exit() 
t = threading.Thread(name='doWait', target = doWait, args=(tb,qapp))
t.start()
\##  ^^^^  gr-CyberRadio  ^^^^
"
	else
		echo "SKIPPING $TEMPLATE"
	fi
done

if [ -f /etc/sysctl.d/uhd-usrp2.conf ]
then
	mv -v /etc/sysctl.d/uhd-usrp2.conf /etc/sysctl.d/90-uhd-usrp2.conf
fi
sysctl -p /etc/sysctl.d/98-gr-cyberradio.conf

