#!/bin/bash
#########################################################
# postinst
#
# Post-installation script that is executed after the
# Debian package is installed
#
# Original Author: DA
# Copyright: (c) 2014 CyberRadio Solutions, Inc.  All rights
#     reserved.
#
#########################################################

# After installing replacement Python code modules, 
# delete previously compiled *.pyc files in order to force
# a recompile.
rm -f $(find /usr/lib/python2.7/dist-packages/CyberRadioDriver -name '*.pyc')

