#!/bin/bash
#########################################################
# \file postinst
#
# \brief Script that is executed after a Debian package
#    is installed
#
# \author DA
# 
# \copyright Copyright (c) 2014-2021 CyberRadio Solutions, Inc.  
#     All rights reserved.
#
#########################################################

# $1 == Action to take (usually "configure", but there are others)
# $2 == Previously installed version (empty if this is a new installation)

# Function to find the installation directory for a given Python module
find_python_module_install_dir()
{
	# $1 == Name of Python module to look for
	python -c "from __future__ import print_function; import sys, os, $1; print(os.path.split(sys.modules['$1'].__file__)[0])"
}

if [ "$1" == "configure" ]
then
    if [ -z "$2" ]
    then
        # New installation
        # -- Nothing to do here, so run /bin/true to return a good error code
        /bin/true
    else
        # Package upgrade
        # -- NOTE: This section is wrapped in set directives because
        #    we expect these actions to fail in certain situations, and
        #    we don't want package configuration to abort when they do.
        set +e
        # -- Find the folder where Python modules are installed
		PYTHON_MODULE_INSTALL_DIR=$(find_python_module_install_dir CyberRadioDriver)
		# -- If this call succeeds, find any existing *.pyc files and
		#    delete them to force a recompile.
		if [ $? -eq 0 ]
		then
			find ${PYTHON_MODULE_INSTALL_DIR} -name "*.pyc" -print0 | xargs -0 -r rm -f
		fi
		set -e
	fi
fi
