#!/bin/bash
#########################################################
# \file prerm
#
# \brief Script that is executed before the Debian package 
#     is uninstalled
#
# \author DA
#
# \copyright Copyright (c) 2014-2021 CyberRadio Solutions, Inc.  
#     All rights reserved.
#
#########################################################

# $1 == Action to take
# -- "upgrade" if the package is being upgraded
# -- "remove" if the package is being removed
# $2 == Version being installed (empty if package is being removed)

# Function to find the installation directory for a given Python module
find_python_module_install_dir()
{
	# $1 == Name of Python module to look for
	python -c "from __future__ import print_function; import sys, os, $1; print(os.path.split(sys.modules['$1'].__file__)[0])"
}

if [ "$1" == "upgrade" ] || [ "$1" == "remove" ]
then
	# Package upgrade or removal
	# -- NOTE: This section is wrapped in set directives because
	#    we expect these actions to fail in certain situations, and
	#    we don't want package configuration to abort when they do.
	set +e
	# -- Find the folder where Python modules are installed
	PYTHON_MODULE_INSTALL_DIR=$(find_python_module_install_dir CyberRadioDriver)
	# -- If this call succeeds, find any existing *.pyc files and
	#    delete them, either to force a recompile or to clean up on 
	#    removal.  Also, if we are removing the package, remove any 
	#    existing __pycache__ directory.
	if [ $? -eq 0 ]
	then
		find ${PYTHON_MODULE_INSTALL_DIR} -name "*.pyc" -print0 | xargs -0 -r rm -f
		if [ "$1" == "remove" ]
		then
			find ${PYTHON_MODULE_INSTALL_DIR} -name "__pycache__" -print0 | xargs -0 -r rm -rf
		fi
	fi
	set -e
fi
