/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vector_nlog10_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3e346605a0dc0404dc03ba262d3f8787)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <CyberRadio/vector_nlog10_ff.h>
// pydoc.h is automatically generated in the build directory
#include <vector_nlog10_ff_pydoc.h>

void bind_vector_nlog10_ff(py::module& m)
{

    using vector_nlog10_ff    = ::gr::CyberRadio::vector_nlog10_ff;


    py::class_<vector_nlog10_ff, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<vector_nlog10_ff>>(m, "vector_nlog10_ff", D(vector_nlog10_ff))

        .def(py::init(&vector_nlog10_ff::make),
           py::arg("n"),
           py::arg("vlen"),
           py::arg("k"),
           D(vector_nlog10_ff,make)
        )
        



        ;




}








