/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vita_udp_rx.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6a4c321362f0c6224782254b4afcc014)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <CyberRadio/vita_udp_rx.h>
// pydoc.h is automatically generated in the build directory
#include <vita_udp_rx_pydoc.h>

void bind_vita_udp_rx(py::module& m)
{

    using vita_udp_rx    = ::gr::CyberRadio::vita_udp_rx;


    py::class_<vita_udp_rx, gr::block, gr::basic_block,
        std::shared_ptr<vita_udp_rx>>(m, "vita_udp_rx", D(vita_udp_rx))

        .def(py::init(&vita_udp_rx::make),
           py::arg("cfg"),
           D(vita_udp_rx,make)
        )
        



        ;




}








