name: gr-CyberRadio build

on:
  push:
    branches: [ main, test_workflow ]

jobs:
  build-ubuntu22-04:
    runs-on: ubuntu-22.04
    steps:
    - name: Get Libcyberradio
      uses: actions/checkout@v2
      with:
        repository: CyberRadio/libcyberradio
        path: './libcyberradio'
      run: ls -lha
    - name: Build and Install libcyberradio
      run: cd libcyberradio/libcyberradio && mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=/usr && make -j && sudo make install
      