name: gr-CyberRadio build

on:
  push:
    branches: [ main, test_workflow ]

jobs:
  build-ubuntu22-04:
    runs-on: ubuntu-22.04
    steps:
    - name: Get Libcyberradio
      uses: actions/checkout@v2
      with:
        repository: CyberRadio/libcyberradio
        path: './libcyberradio'
    - name: Test
      run: ls -lah ./
    - name: Install Build Deps
      run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk2-dev libvolk2.5 cmake
    - name: Build and Install libcyberradio
      run: cd libcyberradio/libcyberradio && mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=/usr && make -j && sudo make install
      